workflows:
  sample-workflow:
    name: Codemagic Sample Workflow

    max_build_duration: 120

    instance_type: mac_mini_m2

    environment:
      node: v18.17.0
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          npx expo prebuild
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
